[package]
name = "acick"
version = "0.0.2"
authors = ["gky360 <gky360@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Tools for programming contests"
repository = "https://github.com/gky360/acick"
documentation = "https://docs.rs/acick"
readme = "README.md"
keywords = ["windows", "cli"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.26"
bytefmt = "0.1.7"
cookie = "0.12.0"
cookie_store = "0.10.0"
dirs = "2.0.2"
fs2 = "0.4.3"
getset = "0.0.9"
heck = "0.3.1"
humantime = "2.0.0"
humantime-serde = "1.0.0"
itertools = "0.8.2"
lazy_static = "1.4.0"
maplit = "1.0.2"
once_cell = "1.3.1"
regex = "1.3.3"
retry = "1.0.0"
reqwest = { version = "0.10.1", default_features = false, features = ["rustls-tls", "blocking"] }
rpassword = "4.0.5"
scraper = "0.11.0"
semver = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.11"
serde_json = "1.0.44"
shellexpand = "1.1.1"
structopt = "0.3.7"
strum = { version = "0.17.1", features = ["derive"] }
tera = "1.0.2"
tokio = { version = "0.2.11", features = ["rt-core", "rt-threaded", "io-util", "time", "process", "macros"] }
