[package]
name = "acick"
version = "0.0.1-pre-1"
authors = ["gky360 <gky360@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Tools for programming contests"
repository = "https://github.com/gky360/acick"
documentation = "https://docs.rs/acick"
readme = "README.md"
keywords = ["windows", "cli"]
categories = ["command-line-utilities"]

[dependencies]
