[package]
name = "acick"
version = "0.0.1-pre-1"
authors = ["gky360 <gky360@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Tools for programming contests"
repository = "https://github.com/gky360/acick"
documentation = "https://docs.rs/acick"
readme = "README.md"
keywords = ["windows", "cli"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.26"
heck = "0.3.1"
lazy_static = "1.4.0"
rpassword = "4.0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.11"
serde_json = "1.0.44"
structopt = "0.3.7"
strum = { version = "0.17.1", features = ["derive"] }
tera = "1.0.2"
