[package]
name = "acick-util"
version = "0.0.6"
authors = ["gky360 <gky360@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/gky360/acick"
documentation = "https://docs.rs/acick"
readme = "README.md"

[dependencies]
anyhow = "1.0.26"
serde = { version = "1.0.104", features = ["derive"] }
shellexpand = "1.1.1"
